# Packaging (and other) tools configuration.
#
# Resources
# ---------
# Packaging documentation:
#   - https://packaging.python.org/en/latest/

[project]
name = "python-package-cookiecutter"
description = "Get the oven ready!"
version = "0.1.0"
requires-python = ">= 3.12"
